### PR TITLE
Uninstall module used on PS 1.6 before using this one

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @Quetzacoalt91, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by Quetzacoalt91** [comment]
Done :)

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by sarahdib** [comment]
The module 1.6 isn't uninstall

**Comment by matks** [comment]
@Quetzacoalt91 As I explained [in this issue](https://github.com/PrestaShop/PrestaShop/issues/26973) I will clean our open PRs backlog and close these stale PRs. But I hope that one day we get some bandwidth to reopen this topic, and when it happens, we'll reopen these PRs, find the issues noticed by QA, fix them and merge them ❤️  .

**Pull request closed without merging**
