### PR TITLE
Fix outdated license headers

### PR DESCRIPTION
**Pull request by matks**
Fix outdated license headers

This PR is created automatically by [Matks PrestaShop Repositories Bulk Editor](https://github.com/matks/prestashop-repos-bulk-editor)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @matks

**Comment by Progi1984** [comment]
@matks Before merging, Could you fix Travis :red_circle: ?

The bug is PHPCSFixer.

**Comment by matks** [comment]
Shall I start working on a Bulk Update PHP CS Fixer Bot ? 😄

**Comment by matks** [comment]
Closed as new headers are now expected - see https://devdocs.prestashop.com/1.7/development/coding-standards/#module-files

**Pull request closed without merging**
