### PR TITLE
Fix the module description

### LINKED ISSUE #32056: ps_currencyselector - wrong wording for the description
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The description of ps_currencyselector doesn't describe well the module, as you can see : 

image

this description is more for the related product than currency selector 

### Expected behavior

wording expected: "Add a currency selector to help visitors from targeted countries purchase on your store."

### Steps to reproduce

1. Have a fresh install of ps 1.7.8.8 or 8.0.1 
2. Go to BO > Improve > Modules > Module Manager 
3. Search "currency" on the search bar 
4. The currency block is in 2.0.1 and the wording is correct 
5. Update the module 
6. /!\ Your currency block is in 2.1.1 and the wording is wrong 

### PrestaShop version(s) where the bug happened

1.7.8.3 - 1.7.8.8 - 8.0.1 

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_currencyselector v2.1.0

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix the module description
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/32056
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/32056

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @mflasquin

**Review by Hlavtox — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @mflasquin ,
Tested on 1.7.8.8, 8.0.1

image

LGTM ,it's QA :heavy_check_mark: 

Thank you :rocket: !

**Comment by nicosomb** [comment]
Thank you @mflasquin !

**Comment by ArnieO** [comment]
The wording is still incorrect.
- Prestashop v8.1.7
- Currency block v2.1.1
image

**Pull request merged**
