### PR TITLE
Replace deprecated ObjectPresenter namespace

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Title says it all
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Everything is supposed to work as before, the behavior is kept identicail. The changed code is related to displaying currency list in Front office.
| Sponsor company | impSolutions

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
could you explain why you remove the php stan neon files ? is it related to this PR ?

**Comment by kpodemski** [comment]
@matthieu-rolland yes, I deleted tests for unsupported PS versions

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @kpodemski ,

Thanks for the PR !

Tested with develop and 1.7.8.x branch.
Imported localization packs, Deleted currency, Checked FO, Switched currency.
It is working well.

It is QA ✅

**Comment by kpodemski** [comment]
Thanks @florine2623 :)

**Pull request merged**
