### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.1.0
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @Hlavtox 
Thanks for the PR ! LGTM QA :heavy_check_mark: 


https://user-images.githubusercontent.com/31663369/212020900-979a50ee-2a17-49a6-a5d5-f9a26016d8ac.mp4

Thank you ! :rocket:

**Comment by Hlavtox** [comment]
@kpodemski Pls merge and fix my merge perms 🥰

**Comment by kpodemski** [comment]
Thanks @Hlavtox !

**Review by Caleydon — COMMENTED** [review]
Previously correct description of the module:
"Adds a block allowing customers to choose their preferred shopping currency."

has been in 2.1.0 changed to incorrect (probably from different module):
"Offer your customers the possibility to buy matching items when on a product page."

**Comment by Hlavtox** [comment]
@Caleydon Yep, good catch - happened here https://github.com/PrestaShop/ps_currencyselector/pull/21.

@kpodemski We need to fix it, do you have a proper description somewhere, or we revert the old one?

**Comment by Hlavtox** [comment]
@PrestaShop/qa-functional Hi, can you create an issue for the previous comments?

**Comment by paulnoelcholot** [comment]
@Hlavtox Yes, we're gonna do that ;)

**Comment by AureRita** [comment]
Hi @Hlavtox ! 

Here is the link of the issue : https://github.com/PrestaShop/PrestaShop/issues/32056

thank you and @Caleydon for the issue !

**Pull request merged**
